/* This file was auto-generated by gulp-shenanigans */

import { IMapRaw } from "../src/components/maps";
import { {{package.name}} } from "../src/{{package.name}}";
import { under } from "./main";
import { stub{{package.name}} } from "./utils/fakes";

function describeMap(map: IMapRaw): void {
    describe(map.name, (): void => {
        for (const i in map.locations) {
            describeLocation(map, i);
        }
    });
}

function describeLocation(map: IMapRaw, locationName: string) {
    under([map.name], locationName, (): void => {
        const fsp: {{package.name}} = stub{{package.name}}();

        sinon.stub(fsp.audioPlayer, "playTheme");

        fsp.maps.setMap(map.name, locationName);
    });
}

describe("maps", (): void => {
    const fsp: {{package.name}} = stub{{package.name}}();

    for (const i in fsp.moduleSettings.maps.library!) {
        describeMap(fsp.moduleSettings.maps.library![i]);
    }
});
